language: python
python:
- 3.6.6
install:
- pip install -r requirements.txt
before_install:
- openssl aes-256-cbc -K $encrypted_ee1c3de85b1f_key -iv $encrypted_ee1c3de85b1f_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
