language: python

python:
  - '3.6.6'
sudo: required
services:
  - postgresql

before_install:
  - openssl aes-256-cbc -K $encrypted_ee1c3de85b1f_key -iv $encrypted_ee1c3de85b1f_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar

env:
  global:
    - DJANGO_SETTINGS_MODULE=config.settings.production

install:
  - pip3 install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE healthcare_test;" -U postgres
  - psql -c "CREATE USER hanoul WITH PASSWORD 'gksdnf11';" -U postgres
  - psql -c "ALTER USER hanoul CREATEDB;" -U postgres
  - python3 app/manage.py makemigrations

script:
  - python3 app/manage.py migrate
  - python3 app/manage.py test

